heat_template_version: 2015-04-30

description: >
  A template showing how to create a cinder volume and attach
  it to a nova instance. The template uses only Heat OpenStack native
  resource types.

parameters:
  image_id:
    type: string
    description: ID of the image to use for the instance to be created.
  instance_type:
    type: string
    description: Type of the instance to be created.
    default: m1.small
  availability_zone:
    type: string
    description: The Availability Zone to launch the instance.
    default: nova
  volume_size:
    type: number
    description: Size of the volume to be created.
    default: 1
    constraints:
      - range: { min: 1, max: 1024 }
        description: must be between 1 and 1024 Gb.

resources:
  private_net:
    type: OS::Neutron::Net
  private_subnet:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: private_net }
      cidr: 11.0.0.0/16
  x_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: private_net }
      fixed_ips:
        - subnet_id: { get_resource: private_subnet }
  nova_instance:
    type: OS::Nova::Server
    properties:
      availability_zone: { get_param: availability_zone }
      metadata:
              admin_pass: aaaaaa
      image: { get_param: image_id }
      flavor: { get_param: instance_type }
      networks:
        - port: { get_resource: x_port }
{% for arg in arg_list %}
  cinder_volume_{{ arg }}:
    type: OS::Cinder::Volume
    properties:
      size: { get_param: volume_size }
      availability_zone: { get_param: availability_zone }
      volume_type: CEPHx
  cinder_volume_attachment_{{ arg }}:
    type: OS::Cinder::VolumeAttachment
    properties:
      volume_id: { get_resource: cinder_volume_{{ arg }} }
      instance_uuid: { get_resource: nova_instance }
{% endfor %}

